[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install --user --break-system-packages -r requirements.txt"
]

[start]
cmd = "python3 bot.py"
