[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.venv"]

[phases.install]
cmds = [
  "python3 -m venv venv",
  "source venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "source venv/bin/activate && python3 bot.py"
